name: Build BL2-F7 Android

on:
  workflow_dispatch:
    inputs:
      build_variant:
        description: "Choose the APK type"
        required: true
        default: instrumented
        type: choice
        options:
          - instrumented
          - release

permissions:
  contents: read

concurrency:
  group: bl2-f7-${{ github.ref }}
  cancel-in-progress: true

env:
  EDEN_SHA: 58c1e20ee58efa3900ba616207d460886214480b
  ANDROID_NDK_VERSION: 28.2.13676358
  ANDROID_CMAKE_VERSION: 3.22.1
